[workspace]
members = ["crates/fusion", "crates/ui"]
default-members = ["crates/fusion"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.98"
fusion = { path = "crates/fusion" }
gpui = { git = "https://github.com/zed-industries/zed" }
smallvec = "1.15.1"