[package]
name = "fusion"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "fusion"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
assets = { path = "../assets" }
gpui.workspace = true
ui = { path = "../ui" }
