[package]
name = "fusion"
version = "0.0.0"
description = "One for all game launcher."
authors = ["Jorge Pardo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fusion_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.3", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc.3", features = [] }
tauri-plugin-os = "2.0.0-rc.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true
