[package]
name = "fusion"
version = "0.0.0"
description = "One for all game launcher."
authors = ["Jorge Pardo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fusion_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.2", features = [] }

[dependencies]
tauri = { version = "2.0.6", features = [] }
tauri-plugin-dialog = "2.0.3"
tauri-plugin-os = "2.0.1"
tauri-plugin-window-state = "2.0.1"
tauri-plugin-single-instance = "2.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
diesel = { version = "2.2.4", features = [
    "sqlite",
    "returning_clauses_for_sqlite_3_35",
] }
diesel_migrations = "2.2.0"
diesel-derive-enum = { version = "2.1.0", features = ["sqlite"] }
libsqlite3-sys = { version = "0.30", features = ["bundled"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.41.0", features = ["full"] }
wrapper-itchio = { path = "../../../crates/wrapper-itchio" }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true
